### ISSUE TITLE
trying to get this to compile, but struggling :)

### ISSUE THREAD

**Issue by patchedsoul** [catacombing/tzompantli#7]
Seems you have local changes to client_toolkit you haven't pushed to your fork. I understand this is a personal + WIP project, but I'm stoked with what you've got going on with this and catacomb, and keen to experiment.

I've been playing with the concept of rewriting something like [Retiled](https://github.com/DrewNaylor/Retiled) within a full Rust stack (smithay, Dioxus, etc.) for the PinePhone. Full disclosure I'm still getting started in Rust coming from Python.

Appreciate any input you're willing to share

**Comment by chrisduerr** [comment]
This is actually part of my attempt to write a little bit of a desktop environment for my PinePhone together with [catacomb](https://github.com/chrisduerr/catacomb). At this point this is mainly to aid with development of that, but it should work relatively well already.

With this disclaimer out of the way, I've updated the repository to use the latest smithay 0.30 beta. Hopefully with smithay and client-toolkit pushed to my own repos, it should prevent force-pushes from screwing things over in the future, but no guarantees there won't be more breakage in the near future until 0.30 is officially released.

Haven't done a ton of testing of the latest commit, but it worked once at least.
